name: Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: buildCache
         
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
      
      - name: Prep
        run: |
          npm install -g pkg
      
      - name: Build EXE
        run: |
          pkg main.js --targets node14-win-x64 --output Deploy.exe --compress Brotli

      # Runs a set of commands using the runners shell
      - name: Ready for zip
        run: |
          mkdir dist
          mkdir dist/Third-Party
          mkdir dist/Info
          xcopy Third-Party dist/Third-Party /s /e /h
          xcopy "For Build" dist /s /e /h
          robocopy ./docs ./dist/Info /COPYALL /E 
          copy Deploy.exe dist
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Mod Framework
          path: dist
